### ISSUE TITLE
Validator state is calculated, not using API status

### ISSUE THREAD

**Issue by BisonDee** [attestantio/go-eth2-client#1]
I would like to understand better how the library is getting the status of the validator. In our use case with Prysm, we are seeing the status a validator with returned status of `Pending_queued` on a Pyrmont validator that is already attesting. My expectation would be "Active_ongoing".

For example, `0xaf63f69ea465a0804dbabed347097228878cba8134c1d04156acc62ab0f3fbf0c1a8994f9521d251f13e69e42da9ac99` is active and has been for some time, yet the status is returned from the lib as `Pending_queued`. This could certainly be user error, but just wanted to check.

**Comment by mcdee** [comment]
Thank you for reporting this issue.  This was due to a failure to obtain the current epoch in the relevant codebase, resulting in the status being evaluated for epoch 0.  This has been addressed in release v0.6.16.

Note that prysm does not at current support the standard HTTP API, which is why this value had to be calculated rather than just relayed from the response.
